import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const formula = localFont({
  src: [
    {path: "./fonts/Formula1-Regular.otf", weight: "400", style: "normal"},
    {path: "./fonts/Formula1-Bold.otf", weight: "700", style: "bold"},
    {path: "./fonts/Formula1-Wide.otf", weight: "900", style: "black"},
  ],
  variable: "--font-formula",
});

export const metadata: Metadata = {
  title: "🏎️ F1 Dashboard 🏎️",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${formula.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
